server:
  port: 8080
spring:
  application:
    name: service-gateway
  cloud:
    cloud:
      nacos:
        discovery:
          server-addr: 127.0.0.1:8848  # Nacos 服务器地址
          namespace: public            # 可选，指定命名空间
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: service-task-manager
          uri: http://localhost:8002
          predicates:
            - Path=/task/**

        - id: service-resource-manager
          uri: http://localhost:8001
          predicates:
            - Path=/resource/**


